/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.fornecedor.view;


import br.com.ifba.fornecedor.controller.FornecedorIController;
import br.com.ifba.fornecedor.entity.Fornecedor;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;



/**
 *
 * @author paulo
 */
@Component
@Slf4j
public class FornecedorListar extends javax.swing.JDialog {
    
    @Autowired
    private FornecedorIController fornecedorControler;
    @Autowired
    private ApplicationContext context;

    /**
     * Creates new form CursoListar
     */
    public FornecedorListar() {
        initComponents();
        bntEditar.setEnabled(false);
        bntDeletar.setEnabled(false);
        setLocationRelativeTo(null);
        
        tblFornecedores.getSelectionModel().addListSelectionListener(e -> {
            boolean linhaSelecionada = tblFornecedores.getSelectedRow() != -1;
            bntEditar.setEnabled(linhaSelecionada);
            bntDeletar.setEnabled(linhaSelecionada);
        });
    }
    
    @PostConstruct
    public void iniciar(){
        loadTableFornecedor();
    }
    
    public final void loadTableFornecedor(){
        try {
            List<Fornecedor> listaFornecedores = fornecedorControler.findAll();

            popularJTable(listaFornecedores);
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Erro",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void popularJTable(List<Fornecedor> fornecedores){
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
        modelo.setNumRows(0);
        
        for(Fornecedor fornecedor : fornecedores){
            modelo.addRow(new Object[]{
                fornecedor.getId(),
                fornecedor.getRazaoSocial(),
                fornecedor.getNomefantasia(),
                fornecedor.getCnpj(),
                fornecedor.getTelefone(),
                fornecedor.getEmail()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        lblListaFornecedores = new javax.swing.JLabel();
        bntCadastrarNovo = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Razão Social", "Nome Fantasia", "CNPJ", "Telefone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFornecedores.setColumnSelectionAllowed(true);
        tblFornecedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFornecedores);
        tblFornecedores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblListaFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaFornecedores.setText("LISTA DE FORNECEDORES");

        bntCadastrarNovo.setText("Cadastrar Novo");
        bntCadastrarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarNovoActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntDeletar.setText("Deletar");
        bntDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                    .addComponent(lblListaFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntCadastrarNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblListaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCadastrarNovo)
                    .addComponent(bntEditar)
                    .addComponent(bntDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void bntCadastrarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarNovoActionPerformed
        
        FornecedorAdicionar viewFornecedorAdicionar = context.getBean(FornecedorAdicionar.class);
        viewFornecedorAdicionar.setLocationRelativeTo(this);
        viewFornecedorAdicionar.setVisible(true);
        this.loadTableFornecedor();
    }//GEN-LAST:event_bntCadastrarNovoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        int linha = tblFornecedores.getSelectedRow();
        
        if (linha != 0){
            Long id = (Long) tblFornecedores.getValueAt(linha, 0);
            
            try{
                Fornecedor fornecedor = fornecedorControler.findById(id);
                
                FornecedorEditar viewFornecedorEditar = context.getBean(FornecedorEditar.class);
                viewFornecedorEditar.setFornecedor(fornecedor);
                viewFornecedorEditar.setVisible(true);
                
                loadTableFornecedor();
                
            } catch (RuntimeException e){
                log.error("Erro ao carregar fornecedor para edição");
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarActionPerformed
        int linha = tblFornecedores.getSelectedRow();
        
        if (linha != 0){
            Long id = (Long) tblFornecedores.getValueAt(linha, 0);
            
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse fornecedor?", "Excluir", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
            if(resposta == JOptionPane.YES_OPTION){
                try{
                    Fornecedor fornecedor = fornecedorControler.findById(id);
                    fornecedorControler.delete(fornecedor);
                    loadTableFornecedor();
                
                } catch (RuntimeException e){
                    log.error("Erro ao carregar fornecedor para exclusão");
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
    }//GEN-LAST:event_bntDeletarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrarNovo;
    private javax.swing.JButton bntDeletar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaFornecedores;
    private javax.swing.JTable tblFornecedores;
    // End of variables declaration//GEN-END:variables
}
