/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.venda.view;

import br.com.ifba.venda.controller.VendaIController;
import br.com.ifba.venda.entity.Venda;
import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.cliente.controller.ClienteIController;
import br.com.ifba.funcionarios.controller.FuncionariosController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import br.com.ifba.produto.entity.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VendaEditar extends javax.swing.JFrame {

    private Venda venda;
    private VendaIController vendaController;
    private FuncionariosController funcionarioController;
    private ClienteIController clienteController;
    private br.com.ifba.produto.controller.IProdutoController produtoController;
    
    private List<Funcionarios> listaFuncionarios;
    private List<Cliente> listaClientes;
     private List<Produto> listaProdutosBanco; 
    private List<Produto> produtosSelecionados = new ArrayList<>(); 
    private float valorTotalVenda = 0.0f;

    public VendaEditar(Venda venda, VendaIController vendaController, 
                   FuncionariosController funcionarioController, 
                   ClienteIController clienteController,
                   br.com.ifba.produto.controller.IProdutoController produtoController) { // Adicionado aqui
        this.venda = venda;
        this.vendaController = vendaController;
        this.funcionarioController = funcionarioController;
        this.clienteController = clienteController;
        this.produtoController = produtoController; 

    initComponents();
    preencherCampos();
    carregarDadosIniciais(); 
    this.setLocationRelativeTo(null);
}
    

    private void preencherCampos() {
        // Exibe os dados atuais da venda
        lblData.setText("Data: " + venda.getDataVenda().toString());
        txtValor.setText(String.valueOf(venda.getValorTotal()));
        
        // Exibe quem são o cliente e funcionário atuais
        lblClienteAtual.setText("Cliente: " + venda.getCliente().getNome());
        lblFuncionarioAtual.setText("Vendedor: " + venda.getFuncionario().getNome());
        
        // Preenche a tabela de itens da venda com o que já foi vendido
        atualizarTabelaItensVenda();
    }
    private void carregarDadosIniciais() {
    DefaultTableModel modelFunc = (DefaultTableModel) tblFuncionario.getModel();
    DefaultTableModel modelCli = (DefaultTableModel) tblCliente.getModel();
    DefaultTableModel modelProd = (DefaultTableModel) tblProdutos.getModel();
    
    modelFunc.setRowCount(0);
    modelCli.setRowCount(0);
    modelProd.setRowCount(0);
    
    // 1. Carrega Funcionários
    listaFuncionarios = funcionarioController.findAll();
    if (listaFuncionarios != null) {
        for (Funcionarios f : listaFuncionarios) {
            modelFunc.addRow(new Object[]{f.getNome(), f.getCargo()});
        }
    }
    
    // 2. Carrega Clientes
    listaClientes = clienteController.listAll(); 
    if (listaClientes != null) {
        for (Cliente c : listaClientes) {
            modelCli.addRow(new Object[]{c.getNome()});
        }
    }

    // 3. Carrega Produtos Disponíveis
    listaProdutosBanco = produtoController.findAll();
    if (listaProdutosBanco != null) {
        for (Produto p : listaProdutosBanco) {
            // Use getPrecoVenda para edição de venda
            modelProd.addRow(new Object[]{p.getNome(), p.getCusto()});
        }
    }
}
    private void atualizarTabelaItensVenda() {
    DefaultTableModel model = (DefaultTableModel) tblVendaMomento.getModel();
    model.setRowCount(0);
    // Venda contém uma lista de produtos
    for (Produto p : venda.getProdutos()) {
        model.addRow(new Object[]{p.getNome(), p.getCusto()});
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        tblProdutos = new javax.swing.JTable();
        lblCliente = new javax.swing.JLabel();
        tblCliente = new javax.swing.JTable();
        lblProdutos = new javax.swing.JLabel();
        tblVendaMomento = new javax.swing.JTable();
        lblVenda = new javax.swing.JLabel();
        tblReceita = new javax.swing.JTable();
        lblReceita = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblIdVenda = new javax.swing.JLabel();
        lblVendaa = new javax.swing.JLabel();
        lblIdVenda1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblNCliente = new javax.swing.JLabel();
        lblClienteAtual = new javax.swing.JLabel();
        lblNCliente1 = new javax.swing.JLabel();
        lblFuncionarioAtual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFuncionario.setText("Funcionario Responsavel");

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome", "cargo"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionario);

        btnAtualizar.setText("Salvar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        txtValor.setText("00.00");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblCliente.setText("Cliente");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblProdutos.setText("Produtos");

        tblVendaMomento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblVenda.setText("Venda");

        tblReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblReceita.setText("Receita");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblIdVenda.setText("ID venda");

        lblVendaa.setText("0");

        lblIdVenda1.setText("Data Venda");

        lblData.setText("0/0/0");

        lblNCliente.setText("Nome Cliente");

        lblClienteAtual.setText("jLabel1");

        lblNCliente1.setText("Nome Funcionario");

        lblFuncionarioAtual.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReceita)
                    .addComponent(tblReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProdutos)
                    .addComponent(tblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblVendaMomento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblValor)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdVenda1)
                                .addGap(18, 18, 18)
                                .addComponent(lblData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdVenda)
                                .addGap(18, 18, 18)
                                .addComponent(lblVendaa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNCliente)
                                .addGap(18, 18, 18)
                                .addComponent(lblClienteAtual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNCliente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFuncionarioAtual))))
                    .addComponent(lblVenda))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProdutos)
                            .addComponent(lblVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tblVendaMomento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblIdVenda1)
                                        .addComponent(lblData))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIdVenda)
                                            .addComponent(lblVendaa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNCliente)
                                    .addComponent(lblClienteAtual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNCliente1)
                                    .addComponent(lblFuncionarioAtual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblValor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFuncionario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblReceita)
                                        .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tblReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
 
    int linhaFunc = tblFuncionario.getSelectedRow();
    if (linhaFunc != -1) {
        venda.setFuncionario(listaFuncionarios.get(linhaFunc));
    }

  
    int linhaCli = tblCliente.getSelectedRow();
    if (linhaCli != -1) {
        venda.setCliente(listaClientes.get(linhaCli));
    }

   
    try {
        vendaController.save(venda);
        JOptionPane.showMessageDialog(this, "Venda atualizada com sucesso!");
        this.dispose();
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), 
                                      "Erro", JOptionPane.ERROR_MESSAGE);
    }      
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um produto na tabela primeiro!");
        return;
    }

 
    Produto produtoSelecionado = listaProdutosBanco.get(linhaSelecionada);


    produtosSelecionados.add(produtoSelecionado);
    valorTotalVenda += produtoSelecionado.getCusto();


    atualizarTabelaItensVenda();


    txtValor.setText(String.format("%.2f", valorTotalVenda));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblClienteAtual;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFuncionarioAtual;
    private javax.swing.JLabel lblIdVenda;
    private javax.swing.JLabel lblIdVenda1;
    private javax.swing.JLabel lblNCliente;
    private javax.swing.JLabel lblNCliente1;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblReceita;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JLabel lblVendaa;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblReceita;
    private javax.swing.JTable tblVendaMomento;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
