/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.venda.view;

import br.com.ifba.venda.controller.VendaIController;
import br.com.ifba.venda.entity.Venda;
import br.com.ifba.cliente.controller.ClienteIController; // Você precisará desses controllers
import br.com.ifba.cliente.entity.Cliente;
import br.com.ifba.funcionarios.controller.FuncionariosController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import br.com.ifba.produto.entity.Produto;
import br.com.ifba.produto.controller.IProdutoController;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VendaAdicionar extends javax.swing.JFrame {
    
    private VendaIController vendaController;
    private FuncionariosController funcionarioController;
    private ClienteIController clienteController;
    private IProdutoController produtoController; 

    private List<Funcionarios> listaFuncionarios;
    private List<Cliente> listaClientes;
    private List<Produto> listaProdutosBanco; 
    private List<Produto> produtosSelecionados = new ArrayList<>(); 
    private float valorTotalVenda = 0.0f;

    public VendaAdicionar(VendaIController vendaController, 
                          FuncionariosController funcionarioController,
                          ClienteIController clienteController,
                          IProdutoController produtoController) {
        this.vendaController = vendaController;
        this.funcionarioController = funcionarioController;
        this.clienteController = clienteController;
        this.produtoController = produtoController;
        initComponents();
        carregarDadosIniciais();
    }

    private void carregarDadosIniciais() {

    DefaultTableModel modelFunc = (DefaultTableModel) tblFuncionario.getModel();
    DefaultTableModel modelCli = (DefaultTableModel) tblCliente.getModel();
    DefaultTableModel modelProd = (DefaultTableModel) tblProdutos.getModel();
    
    modelFunc.setRowCount(0);
    modelCli.setRowCount(0);
    modelProd.setRowCount(0);
    
    // 1. Carrega Funcionários
    listaFuncionarios = funcionarioController.findAll();
    if (listaFuncionarios != null) {
        for (Funcionarios f : listaFuncionarios) {
            modelFunc.addRow(new Object[]{f.getNome(), f.getCargo()});
        }
    }
    
    // 2. Carrega Clientes usando listAll() da sua interface
    listaClientes = clienteController.listAll(); 
    if (listaClientes != null) {
        for (Cliente c : listaClientes) {
            modelCli.addRow(new Object[]{c.getNome()});
        }
    }

    // 3. Carrega Produtos Disponíveis para caso o usuário queira adicionar novos itens
    listaProdutosBanco = produtoController.findAll();
    if (listaProdutosBanco != null) {
        for (Produto p : listaProdutosBanco) {
            modelProd.addRow(new Object[]{p.getNome(), p.getCusto()});
        }
    }
}
    
    private void atualizarTabelaVenda() {
  
    DefaultTableModel modelVenda = (DefaultTableModel) tblVendaMomento.getModel(); 
    modelVenda.setRowCount(0);

    for (Produto p : produtosSelecionados) {
        modelVenda.addRow(new Object[]{
            p.getNome(),
            p.getCusto() //
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        tblProdutos = new javax.swing.JTable();
        lblCliente = new javax.swing.JLabel();
        tblCliente = new javax.swing.JTable();
        lblProdutos = new javax.swing.JLabel();
        tblVendaMomento = new javax.swing.JTable();
        lblVenda = new javax.swing.JLabel();
        tblReceita = new javax.swing.JTable();
        lblReceita = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFuncionario.setText("Funcionario Responsavel");

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome", "cargo"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionario);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        txtValor.setText("00.00");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblCliente.setText("Cliente");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblProdutos.setText("Produtos");

        tblVendaMomento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblVenda.setText("Venda");

        tblReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));

        lblReceita.setText("Receita");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReceita)
                    .addComponent(tblReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProdutos)
                    .addComponent(tblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tblVendaMomento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValor))
                            .addComponent(lblVenda))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReceita)
                                    .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tblReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblProdutos)
                                    .addComponent(lblVenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tblProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tblVendaMomento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValor)
                                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton1)))
                                .addGap(0, 134, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       Venda venda = new Venda();
    
    // 1. Seleção de Funcionário (Correto)
    int linhaFunc = tblFuncionario.getSelectedRow();
    if (linhaFunc == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um Funcionário!");
        return;
    }
    venda.setFuncionario(listaFuncionarios.get(linhaFunc));

    // 2. Seleção de Cliente (CORREÇÃO: Usar a tabela de Clientes, não de Produtos)
    int linhaCli = tblCliente.getSelectedRow(); // Certifique-se que o nome é tblCliente
    if (linhaCli == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um Cliente!");
        return;
    }
    venda.setCliente(listaClientes.get(linhaCli));

    // 3. Data e Status (Conforme o diagrama de classes)
    venda.setDataVenda(LocalDateTime.now());
   
    
    // 4. Produtos (Usando a lista que o botão "+" preencheu)
    if (produtosSelecionados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Adicione ao menos um produto à venda!");
        return;
    }
    venda.setProdutos(new ArrayList<>(produtosSelecionados));

    // 5. Valor Total (Melhor usar a variável acumulada no botão "+")
    venda.setValorTotal(this.valorTotalVenda);

    // 6. Seleção de Receita (Opcional, mas presente no diagrama)
    int linhaRec = tblReceita.getSelectedRow();
    if (linhaRec != -1) {
        // Se houver uma lista de receitas carregada:
        // venda.setReceita(listaReceitas.get(linhaRec));
    }

    // 7. Salvar via Controller
    try {
        vendaController.save(venda);
        JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!");
        this.dispose();
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
            
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um produto na tabela primeiro!");
        return;
    }

 
    Produto produtoSelecionado = listaProdutosBanco.get(linhaSelecionada);


    produtosSelecionados.add(produtoSelecionado);
    valorTotalVenda += produtoSelecionado.getCusto();


    atualizarTabelaVenda();


    txtValor.setText(String.format("%.2f", valorTotalVenda));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblReceita;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblReceita;
    private javax.swing.JTable tblVendaMomento;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
