/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.venda.view;

import br.com.ifba.venda.controller.VendaIController;
import br.com.ifba.venda.entity.Venda;
import br.com.ifba.cliente.controller.ClienteIController;
import br.com.ifba.funcionarios.controller.FuncionariosController;
import br.com.ifba.produto.controller.IProdutoController;
import jakarta.annotation.PostConstruct;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class VendaListar extends javax.swing.JFrame {

    @Autowired
    private VendaIController vendaController;

    @Autowired
    private FuncionariosController funcionarioController;

    @Autowired
    private ClienteIController clienteController;

    @Autowired
    private IProdutoController produtoController;

    private List<Venda> listaVendas;

    public VendaListar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @PostConstruct
    public void init() {
        preencherTabela();
    }

    private void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
        model.setRowCount(0);

        listaVendas = vendaController.findAll();

        if (listaVendas != null) {
            for (Venda venda : listaVendas) {

                model.addRow(new Object[]{
                    venda.getId(),
                    venda.getDataVenda().toString(),
                    venda.getValorTotal(),
                    venda.getFuncionario().getNome(),
                    venda.getCliente().getNome(),
                    venda.getReceita() != null ? venda.getReceita().getNomeRemedio() : "Sem Receita"
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sclClientesLista = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnResetar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "data de venda", "valor", "funcionario", "cliente", "receita"
            }
        ));
        sclClientesLista.setViewportView(tblVendas);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnResetar.setText("R");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesqusar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblNumero.setText("Numero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclClientesLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnResetar)
                        .addComponent(btnExcluir)
                        .addComponent(btnEditar)
                        .addComponent(btnAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclClientesLista, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        VendaAdicionar telaAdd = new VendaAdicionar(vendaController, funcionarioController, clienteController, produtoController);

        telaAdd.setVisible(true);

        preencherTabela();

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tblVendas.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma venda para excluir!");
            return;
        }

        Venda vendaSelecionada = listaVendas.get(linhaSelecionada);

        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir a venda ID: " + vendaSelecionada.getId() + "?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            vendaController.deleteById(vendaSelecionada.getId());
            preencherTabela();
            JOptionPane.showMessageDialog(this, "Venda excluída com sucesso!");
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int linhaSelecionada = tblVendas.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma VENDA para editar!",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Venda vendaSelecionada = listaVendas.get(linhaSelecionada);

        VendaEditar telaEditar = new VendaEditar(
                vendaSelecionada,
                vendaController,
                funcionarioController,
                clienteController,
                produtoController
        );

        telaEditar.setVisible(true);

        preencherTabela();

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        // TODO add your handling code here:
        preencherTabela();
    }//GEN-LAST:event_btnResetarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nomePesquisado = txtPesquisa.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
        model.setRowCount(0);

        if (nomePesquisado.isEmpty()) {
            preencherTabela();
            return;
        }

        for (Venda venda : listaVendas) {
            // Pesquisa pelo nome do cliente vinculado à venda
            if (venda.getCliente().getNome().toLowerCase().contains(nomePesquisado)) {
                model.addRow(new Object[]{
                    venda.getId(),
                    venda.getDataVenda().toString(),
                    venda.getValorTotal(),
                    venda.getFuncionario().getNome(),
                    venda.getCliente().getNome()
                });
            }
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnResetar;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JScrollPane sclClientesLista;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
