/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.convenio.view;

import br.com.ifba.convenio.controller.ConvenioIController;
import br.com.ifba.convenio.entity.Convenio;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author ianep
 */
@Component
public class ConvenioListar extends javax.swing.JFrame {
    
    @Autowired
    private ConvenioIController convenioController;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConvenioListar.class.getName());

    
    public ConvenioListar() {
        initComponents();
        tblConvenios.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"ID", "Nome", "Desconto"}
        ));

    tblConvenios.getColumnModel().getColumn(0).setMinWidth(0);
    tblConvenios.getColumnModel().getColumn(0).setMaxWidth(0);
    tblConvenios.getColumnModel().getColumn(0).setPreferredWidth(0);

        this.setLocationRelativeTo(null); 
        
        
        adicionarListenerSelecaoTabela(); 
    
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConvenios = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblConvenios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConvenios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    ConvenioRegistrar tela = new ConvenioRegistrar(this.convenioController);
        tela.setVisible(true);

    tela.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
        preencherTabela();
    }
});    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
int linhaSelecionada = tblConvenios.getSelectedRow();
if (linhaSelecionada != -1) {
    
    int linhaModelo = tblConvenios.convertRowIndexToModel(linhaSelecionada);

    Long id = (Long) tblConvenios.getModel().getValueAt(linhaModelo, 0);

    try {
        Convenio convenioSelecionado = this.convenioController.findById(id);

        ConvenioEditar tela = new ConvenioEditar(this, true, convenioSelecionado, this.convenioController);
        tela.setVisible(true);

        preencherTabela();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar dados: " + e.getMessage());
    }
}    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        
            int linhaSelecionada = tblConvenios.getSelectedRow();
        if (linhaSelecionada != -1) {
            int linhaModelo = tblConvenios.convertRowIndexToModel(linhaSelecionada);
    
        Long id = (Long) tblConvenios.getModel().getValueAt(linhaModelo, 0);
         String nome = (String) tblConvenios.getModel().getValueAt(linhaModelo, 1);

        int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir: " + nome + "?", 
            "Excluir Convênio", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            Convenio c = new Convenio();
            c.setId(id);
            
            this.convenioController.delete(c);
            
            preencherTabela();
            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
        }
    }
}

    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConvenioListar().setVisible(true));
    }
    
    public void preencherTabela() {
    var model = (javax.swing.table.DefaultTableModel) tblConvenios.getModel();
    model.setRowCount(0); // Limpa tabela

    try {
        List<Convenio> lista = convenioController.findAll(); // Busca no banco
        for (Convenio c : lista) {
            model.addRow(new Object[]{ c.getId(), c.getNome(), c.getDesconto() });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
}
    
    
    private void adicionarListenerSelecaoTabela() {
    // Pega o modelo de seleção da tabela e adiciona um "espião" (listener)
    tblConvenios.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        @Override
        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
            // 'getValueIsAdjusting' evita que o evento dispare duas vezes (ao clicar e ao soltar)
            // Queremos apenas o evento final.
            if (!e.getValueIsAdjusting()) {
                // Verifica se existe alguma linha selecionada (diferente de -1)
                boolean linhaSelecionada = tblConvenios.getSelectedRow() != -1;
                
                // Habilita ou desabilita os botões baseado nisso
                btnEditar.setEnabled(linhaSelecionada);
                btnExcluir.setEnabled(linhaSelecionada);
            }
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblConvenios;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
