/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.convenio.view;

import br.com.ifba.convenio.controller.ConvenioIController;
import br.com.ifba.convenio.entity.Convenio;
import javax.swing.JOptionPane;

/**
 *
 * @author ianep
 */
public class ConvenioEditar extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConvenioEditar.class.getName());

    private Convenio convenio;
    private ConvenioIController controller;

// Construtor completo
    public ConvenioEditar(java.awt.Frame parent, boolean modal, Convenio convenio, ConvenioIController controller) {
        super(parent, modal);
        initComponents();

        this.convenio = convenio;
        this.controller = controller;

        preencherCampos(); // Carrega os dados nos campos
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JToggleButton();
        txtNomeEdit = new javax.swing.JTextField();
        txtDescontoEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        btnSalvar.setText("Editar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditActionPerformed(evt);
            }
        });

        txtDescontoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Desconto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnSalvar)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(txtDescontoEdit))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDescontoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            convenio.setNome(txtNomeEdit.getText());

            String valor = txtDescontoEdit.getText().replace(",", ".");
            convenio.setDesconto(new java.math.BigDecimal(valor));

            this.controller.update(convenio); // Manda atualizar

            JOptionPane.showMessageDialog(this, "Atualizado!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDescontoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    private void preencherCampos() {
        txtNomeEdit.setText(convenio.getNome());
        txtDescontoEdit.setText(String.valueOf(convenio.getDesconto()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDescontoEdit;
    private javax.swing.JTextField txtNomeEdit;
    // End of variables declaration//GEN-END:variables
}
