/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.compra.view;
import br.com.ifba.compra.controller.CompraIController;
import br.com.ifba.compra.entity.Compra;
import br.com.ifba.funcionarios.controller.FuncionariosController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC
 */

public class CompraAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompraAdicionar.class.getName());

    /**
     * Creates new form CompraAdicionar
     */
    
    private List<Funcionarios> lista;
    
    private FuncionariosController funcionarioController;
    
    private CompraIController controller;
    
    public CompraAdicionar(java.awt.Frame parent, boolean modal, CompraIController controller, FuncionariosController funcionarioController){
        this.controller = controller;
        this.funcionarioController = funcionarioController;
        initComponents();
        funcionariosListar();
    }

    private void funcionariosListar(){
        DefaultTableModel model = (DefaultTableModel) tblFuncionario.getModel();
        model.setRowCount(0);
        
        lista = funcionarioController.findAll();
        
        if (lista != null) {
            for (Funcionarios f : lista) {
                model.addRow(new Object[]{
                    f.getNome(),
                    f.getCargo()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroNF = new javax.swing.JLabel();
        txtNumeroNF = new javax.swing.JTextField();
        lblChaveNF = new javax.swing.JLabel();
        txtChaveNF = new javax.swing.JTextField();
        lblDataEmissao = new javax.swing.JLabel();
        spnDia = new javax.swing.JSpinner();
        spnMes = new javax.swing.JSpinner();
        spnAno = new javax.swing.JSpinner();
        lblFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNumeroNF.setText("Numero da Nota Fiscal");

        txtNumeroNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroNFActionPerformed(evt);
            }
        });

        lblChaveNF.setText("Chave da Nota Fiscal");

        lblDataEmissao.setText("Data de Emissão");

        spnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnAno.setModel(new javax.swing.SpinnerNumberModel(2026, 1, LocalDate.now().getYear(), 1));

        lblFuncionario.setText("Funcionario Responsavel");

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome", "cargo"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionario);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        txtValor.setText("00.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNumeroNF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroNF)
                        .addComponent(lblChaveNF)
                        .addComponent(txtChaveNF))
                    .addComponent(lblDataEmissao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFuncionario)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroNF)
                    .addComponent(lblFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumeroNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChaveNF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChaveNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataEmissao)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroNFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroNFActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Compra compra = new Compra();
        
        
        compra.setChaveNF(txtChaveNF.getText());
        
        compra.setNumeroNF(txtNumeroNF.getText());
        
        try {
        int ano = (Integer) spnAno.getValue();
        int mes = (Integer) spnMes.getValue();
        int dia = (Integer) spnDia.getValue();

        LocalDate data = LocalDate.of(ano, mes, dia);
        compra.setDataEmissao(data);
        
        } catch (DateTimeException e) { //Se a data for invalida como dia 31 de fevereiro
        JOptionPane.showMessageDialog(
        this,
        "Data inválida!",
        "Erro",
        JOptionPane.ERROR_MESSAGE
        );
        return;
        }
        
        compra.setDataLancamento(LocalDate.now());
        
        //Seleção de Funcionario
        int linhaSelecionada = tblFuncionario.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Selecione um Funcionario!",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        Funcionarios selecionado = lista.get(linhaSelecionada);
        
        compra.setFuncionario(selecionado);
        
        compra.setStatus("Concluida");
        
        try{//tenta transformar o texto em double
        compra.setValorTotal(Double.parseDouble(txtValor.getText()));
        }catch(NumberFormatException e) {
        System.out.println("Erro: A string não é um número válido.");
        }
        
        //tenta salvar a compra
        try{
            controller.save(compra);
            JOptionPane.showMessageDialog(this, "Compra cadastrada com sucesso!");
            this.dispose();
        } catch(RuntimeException a) {
        JOptionPane.showMessageDialog(this,
            "Falha ao salvar a compra: " + a.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        }
            
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChaveNF;
    private javax.swing.JLabel lblDataEmissao;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblNumeroNF;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtChaveNF;
    private javax.swing.JTextField txtNumeroNF;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
