/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.compra.view;

import br.com.ifba.compra.controller.CompraIController;
import br.com.ifba.compra.entity.Compra;
import br.com.ifba.funcionarios.controller.FuncionariosController;
import br.com.ifba.funcionarios.entity.Funcionarios;
import java.util.List;
import javax.swing.JOptionPane;
import java.time.DateTimeException;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class CompraEditar extends javax.swing.JFrame {

    private Compra compra;
    private CompraIController controller;
    
    private List<Funcionarios> lista;
    private FuncionariosController funcionarioController;

    public CompraEditar(Compra compra, CompraIController controller, FuncionariosController funcionarioController) {
        this.compra = compra;
        this.controller = controller;
        this.funcionarioController = funcionarioController;

        initComponents();
        preencherCampos();
        funcionariosListar();
    }

    private void preencherCampos() {
        txtNumero.setText(compra.getNumeroNF());
        txtChave.setText(compra.getChaveNF());
        lblDataAtual.setText(compra.getDataEmissao().getDayOfMonth() + "/" + compra.getDataEmissao().getMonthValue()
        + "/" + compra.getDataEmissao().getYear());
        lblFuncionario.setText("Funcionario:" + compra.getFuncionario().getNome());
        
    }
    
    private void funcionariosListar(){
        DefaultTableModel model = (DefaultTableModel) tblFuncionario.getModel();
        model.setRowCount(0);
        
        lista = funcionarioController.findAll();
        
        if (lista != null) {
            for (Funcionarios f : lista) {
                model.addRow(new Object[]{
                    f.getNome(),
                    f.getCargo()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroNF = new javax.swing.JLabel();
        lblChaveNF = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtChave = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        lblDataAtual = new javax.swing.JLabel();
        spnDia = new javax.swing.JSpinner();
        spnMes = new javax.swing.JSpinner();
        spnAno = new javax.swing.JSpinner();
        boxStatus = new javax.swing.JComboBox<>();
        jscPainel = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        lblFuncionario = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumeroNF.setText("Numero NF");

        lblChaveNF.setText("Chave NF");

        lblData.setText("Data:");

        lblStatus.setText("Status:");

        txtNumero.setText("000");
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtChave.setText("000");
        txtChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChaveActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblDataAtual.setText("00/00/00");

        spnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnAno.setModel(new javax.swing.SpinnerNumberModel(2000, 1, LocalDate.now().getYear(), 1));

        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluida", "Cancelada", "EmAndamento" }));

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome", "Cargo"
            }
        ));
        jscPainel.setViewportView(tblFuncionario);

        lblFuncionario.setText("funcionario:");

        lblValor.setText("Valor");

        txtValor.setText("00.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroNF)
                    .addComponent(lblChaveNF)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataAtual))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtChave, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStatus)
                                .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFuncionario)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jscPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroNF)
                    .addComponent(lblFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChaveNF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(lblDataAtual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jscPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChaveActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        compra.setNumeroNF(txtNumero.getText());
        compra.setChaveNF(txtChave.getText());
        
        try {
        int ano = (Integer) spnAno.getValue();
        int mes = (Integer) spnMes.getValue();
        int dia = (Integer) spnDia.getValue();

        LocalDate data = LocalDate.of(ano, mes, dia);
        compra.setDataEmissao(data);
        
        } catch (DateTimeException e) { //Se a data for invalida como dia 31 de fevereiro
        JOptionPane.showMessageDialog(
        this,
        "Data inválida!",
        "Erro",
        JOptionPane.ERROR_MESSAGE
        );
        return;
        }
        
        //Seleção de Funcionario
        int linhaSelecionada = tblFuncionario.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Selecione um Funcionario!",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        Funcionarios selecionado = lista.get(linhaSelecionada);
        
        compra.setFuncionario(selecionado);
        
        try{//tenta transformar o texto em double
        compra.setValorTotal(Double.parseDouble(txtValor.getText()));
        }catch(NumberFormatException e) {
        System.out.println("Erro: A string não é um número válido.");
        }
        
        compra.setStatus(boxStatus.getSelectedItem().toString());
        
        try{
        controller.save(compra);
        JOptionPane.showMessageDialog(
            this,
            "Compra atualizada com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        this.dispose();
        }catch(RuntimeException a) {
        JOptionPane.showMessageDialog(this,
            "Falha ao Atualizar a compra: " + a.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        }
        

        this.dispose(); // fecha a tela
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JScrollPane jscPainel;
    private javax.swing.JLabel lblChaveNF;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblNumeroNF;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
